### ISSUE TITLE
Pressing just [Enter] in the dr console crashes it

### ISSUE THREAD

**Issue by Electrux** [Ewpratten/dr#1]
## Issue
When the [Enter] key is pressed without any input, the program crashes.

## Steps to reproduce
Start the program and simply press [Enter]

## Output
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./dr/__main__.py", line 81, in <module>
  File "./dr/__main__.py", line 39, in isValidCommand
IndexError: string index out of range
```

## Expected Output
```
Empty string entered. Use <help command> for help.
```

**Comment by Ewpratten** [comment]
know issue. should be fixed now.

it was caused by an incorrect entry in an array.
